### ISSUE TITLE
Resize bar jumps to x=0

### ISSUE THREAD

**Issue by coolworx** [martinnov92/React-Splitters#15] opened 2018-06-07 19:28 UTC
Great component! I would like to use it but in vertical, postponed mode, the resize bar jumps to the left margin of the screen. It doesn't always happen, though. If you cannot reproduce I can send you the steps. I am seeing this in Chrome/Mac.

**Comment by martinnov92** [comment] 2018-06-16 21:07
Hello @coolworx, yes I am maintaining this repo, I just have been busy lately, but I will try to fix this asap. Thank you

**Comment by coolworx** [comment] 2018-06-16 21:47
Super, thank you. Let me know if you need any more details in order to reproduce the problem I am seeing.

Cheers,
Marius
________________________________

**Comment by martinnov92** [comment] 2018-08-23 18:32
Hello, could you please provide some example? I would like to fix this problem, but in my example it is working ok, but it is very simple example. Thank you

**Comment by josdejong** [comment] 2018-10-04 11:39
Thanks for sharing this Splitter component @martinnov92 , it works like a charm!

I noticed this bug of the bar sometimes jumping to zero too. 

To reproduce (tested on Chrome and Firefox): 

- Open the demo https://martinnov92.github.io/React-Splitters/
- Drag the splitter between 1 and 2 once a few pixels to left or right.
- Now, drag it again, start dragging your mouse from the icon with the two vertical lines in the middle of the splitter. The splitter jumps to the left.
- Also reproducable by *clicking* on the splitter between 1 and 2 after having dragged it once a bit. Don't drag, just click. In most cases, the splitter jumps a few pixels to the left or right after clicking.  When clicking the icon with the two vertical lines in the middle, it jumps to the left.

I hope this helps finding the cause of the issue.

**Comment by martinnov92** [comment] 2018-12-20 21:40
Hello, this has been fixed in new version 1.2.0

**Closed by martinnov92** 2018-12-20 21:40 UTC
Labels: bug

**Comment by josdejong** [comment] 2018-12-21 08:12
Thanks @martinnov92, I can confirm that the issue is resolved in the latest version :+1:
