### ISSUE TITLE
Buggy when using iframes

### ISSUE THREAD

**Issue by aJonathanSchneider** [martinnov92/React-Splitters#14] opened 2018-05-04 10:22 UTC
Hi, thanks a lot for sharing this project, it's pretty useful.

I've found one issue when I was trying to use iframe as one of the children. In Chrome, when I'm dragging and the mouse enters the iframe, the dragging doesn't update. When I get out of the iframe, it'll continue dragging even if I released the mouse. Maybe setting `pointer-events: none` in css when starting to drag could fix this?

**Comment by martinnov92** [comment] 2018-12-23 08:05
Hello, I was unable to reproduce this issue, so I will close this for now.
If you are able to provide some example I will gladly reopen it and try to fix it.
I used it like this:
```
    <Splitter
      position="horizontal"
      primaryPaneMaxHeight="80%"
      primaryPaneMinHeight={0}
      primaryPaneHeight="400px"
      dispatchResize={true}
      postPoned={true}
    >
      <Splitter
        position="vertical"
        primaryPaneMaxWidth="80%"
        primaryPaneMinWidth={0}
        primaryPaneWidth="400px"
        postPoned={false}
      >
        <div />
        <div />
      </Splitter>
      <iframe src="http://www.webpage.com" width="1000" height="300" />
    </Splitter>
```
and had no issue.

**Closed by martinnov92** 2018-12-23 08:05 UTC
Labels: next
